### ISSUE TITLE
如何去掉播放界面上的水印？

### ISSUE THREAD

**Issue by gentleboy** [iMoreApps/ffmpeg-avplayer-for-ios#12]
您好！我想请问一下，如何去掉播放界面上的“DEMO VERSION”这几个红色的文字水印？

**Comment by MrRainQ** [comment]
_glView = [_avplayController drawableView];               
    [_glView.subviews enumerateObjectsUsingBlock:^(UILabel *obj, NSUInteger idx, BOOL *stop) {
           obj.hidden = YES;
    }];
上面的代码就可以去掉水印！！
记得给好评哦！！！亲

**Comment by gentleboy** [comment]
按照您给的方法，可以把水印去掉！Thank you very much!anzhao

**Comment by gentleboy** [comment]
按照您提供的方法，可以把水印去掉！Thank you very much!

**Comment by iMoreApps** [comment]
试用版仅供演示，在正式产品中使用会存在未知风险，谢谢。

**Comment by beheyegao** [comment]
为什么我的demo水印没有去掉
