### ISSUE TITLE
ffmpeg库冲突问题

### ISSUE THREAD

**Issue by gentleboy** [iMoreApps/ffmpeg-avplayer-for-ios#13]
您好，我最近在做一个app的视频监控和视频播放两个模块。视频监控用的是某公司的SDK（不开源，只提供了.a 文件和头文件），视频播放打算用您这个SDK（因为我要播放flv格式的网络视频，而iOS自带的播放器类并不支持flv）。单独的两个模块的功能我都实现了，但是将这两个模块合到一个app里面去的时候发生了符号冲突，原因是视频监控SDk使用了旧版本的ffmpeg并对源码做了些许改动，ffmpeg-avplayer-for-ios也用到了ffmpeg。这就导致在链接的时候出现了很多 duplicate symbol 错误。我之前也试过其他的播放器，还是一样的符号冲突问题，因为都用到了ffmpeg。视频监控和视频播放这两个功能我都很需要，我在网上搜了一些办法来试图解决符号冲突问题，但都以失败告终。我们服务器端的视频格式几乎都是flv的，服务器那边是不会将flv转成MP4的。我们今天尝试用网页播放器，但由于ios不支持flash，还是以失败告终。如今之计，貌似只能自己写一个能播放flv的播放器，并保证和视频监控不会冲突。但说实话，我对视频播放并不熟，自己写播放器不太现实。。。我被这个问题困了快一个月了。。不知道您是否有办法帮助我一下？万分感谢~

**Comment by iMoreApps** [comment]
这个只有一种解决办法，统一两者的FFmpeg版本，除此之外别无他法。如果您购买我们的专业版，我们可以给您提供额外的定制来解决该问题。谢谢。
