### ISSUE TITLE
视频定点播放时，经常停止过段时间会直接到结束位置

### ISSUE THREAD

**Issue by ranshon** [iMoreApps/ffmpeg-avplayer-for-ios#16]

**Comment by iMoreApps** [comment]
是否是网络视频?

**Comment by ranshon** [comment]
嗯 是的 rmpt 协议的网络视频

发自我的 iPhone

**Comment by iMoreApps** [comment]
能否提供一个测试源给我们？

**Comment by ranshon** [comment]
你试试 这个链接 rtmp://61.133.116.49/flv/mp4:n2014/jxjy/kc213/kj2276/fc/gdxxkjzd201401.mp4    在播放时  拖动进度条  会卡  或者进度条拖不过去   ‍
 





------------------ 原始邮件 ------------------
发件人: "imoreapps";<notifications@github.com>;
发送时间: 2015年3月5日(星期四) 上午9:08
收件人: "iMoreApps/ffmpeg-avplayer-for-ios"<ffmpeg-avplayer-for-ios@noreply.github.com>; 
抄送: "印语轩"<1019362424@qq.com>; 
主题: Re: [ffmpeg-avplayer-for-ios] 视频定点播放时，经常停止过段时间会直接到结束位置 (#16)




能否提供一个测试源给我们？

**Comment by iMoreApps** [comment]
感谢您提供的测试源。您的这个源音频流的时间戳好像是无效的，VLC也是无法seek的。

**Comment by ranshon** [comment]
网页的可以呢，并且别家的vitamio。效果还可以。但不知道他们怎么处理的

发自我的 iPhone

**Comment by iMoreApps** [comment]
Vitamio? 好的，我们会持续跟进这个问题的，谢谢@

**Comment by zuolingfeng** [comment]
请问这个支持smb流直接播放么？比如smb://192.168.1.102/share/test.mp4

**Comment by iMoreApps** [comment]
正式版是支持SMB流播放的，谢谢。

**Comment by zuolingfeng** [comment]
正式版？我在github上下载代码运行后，输入smb://10.21.103.13/admin/Desktop/123.mp4 ，弹出播放失败。。难道github上的不是正式版？

**Comment by iMoreApps** [comment]
github上只是个DEMO，目的是给我们的客户演示框架的内部使用流程。如需正式版请通过mail联系我们:imoreapps@gmail.com. 谢谢。
