### ISSUE TITLE
Does any solution to shorter RTSP delay time? and the delay time more longer for longer connection time. 

### ISSUE THREAD

**Issue by YenKaiHuang** [iMoreApps/ffmpeg-avplayer-for-ios#19]
Test environment:
1. Use  ffmpeg-avplayer-for-ios to stream RTSP from a Web camera.
2. Another phone record them and monitor the delay time.
the iOS version: 8.0.2

Test result:
After 1 min connection, the RTSP Streaming delay about 5 sec.
After 4 min connection, the RTSP Streaming delay about 7 sec.
Does any solution for shorten the RTSP Streaming delay time?

Please reference below images:
![1 min](https://cloud.githubusercontent.com/assets/5220478/6661173/b2cb9426-cbe2-11e4-9c85-32a1a07ca4db.png)
![4 min](https://cloud.githubusercontent.com/assets/5220478/6661178/c7fb0e4e-cbe2-11e4-9c61-be30b0055b26.png)

**Comment by iMoreApps** [comment]
The test environment is ready, we are reviewing it now, thanks.

**Comment by iMoreApps** [comment]
We just submit an update, this update added rich options of ffmpeg library support for openMedia interface, you can adjust the probesize parameter to test the latency.

![image](https://cloud.githubusercontent.com/assets/3189965/6801983/62f3a476-d267-11e4-96c4-6d1026de0677.png)
