### ISSUE TITLE
Build fails for iPhone 4s simulator

### ISSUE THREAD

**Issue by igorkravchenko** [iMoreApps/ffmpeg-avplayer-for-ios#20]
Latest update of trail.AVPTFramework fails for iPhone4s simulator with such error:

Undefined symbols for architecture i386:
  "_RTMP_Close", referenced from:
      _rtmp_close in trail.AVPTFramework
  "_RTMP_Connect", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_ConnectStream", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_EnableWrite", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_Init", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_LogSetCallback", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_LogSetLevel", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_Pause", referenced from:
      _rtmp_read_pause in trail.AVPTFramework
  "_RTMP_Read", referenced from:
      _rtmp_read in trail.AVPTFramework
  "_RTMP_SendSeek", referenced from:
      _rtmp_read_seek in trail.AVPTFramework
  "_RTMP_SetupURL", referenced from:
      _rtmp_open in trail.AVPTFramework
  "_RTMP_Socket", referenced from:
      _rtmp_get_file_handle in trail.AVPTFramework
  "_RTMP_Write", referenced from:
      _rtmp_write in trail.AVPTFramework
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there any solution for this?

**Comment by iMoreApps** [comment]
The framework doesn't contain the i386 version, so please switch into the iPhone 5s/6/6p simulator.
