### ISSUE TITLE
Has anyone used this to autoplay videos in a feed like Vine, Instagram, or Facebook?

### ISSUE THREAD

**Issue by mitchellporter** [iMoreApps/ffmpeg-avplayer-for-ios#21]
I've been doing research and it looks like if you want to have auto-playing videos in a feed of table view cells or collectionview cells that you want to use AVPlayer.

However, rather than start from scratch with AVPlayer, I'd like to use this framework. I was hoping it had subclasses of AVPlayer, but it doesn't.

So now I'm wondering if this framework will be able to accomplish the above. Has anyone been able to use this framework to create an app like Vine, Instagram, or Facebook with auto-playing videos in a scrollable feed?

**Comment by iMoreApps** [comment]
Great. We are integrating the native AVPlayer component now, we will provide it on next update.
