### ISSUE TITLE
About RTSP have digest authentication can not working

### ISSUE THREAD

**Issue by Vanmm** [iMoreApps/ffmpeg-avplayer-for-ios#26]
HI, I have trouble in playing Video from IPCarema using RTSP protocol, when IPCarema have RTSP digest authentication , apps can not working , I'm sure the address is right.

Have some advice to me ?

thank you !~

**Comment by iMoreApps** [comment]
Ffmpeg doesn't support RTSP protocol with authentication, we are integrating the live555 library into the avplayer framework.
